# Generated by Django 3.2.9 on 2021-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('NameEn', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('IsActive', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
    ]
