# Generated by Django 3.2.9 on 2021-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=150, verbose_name='نام کامل')),
                ('Email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('Comment', models.TextField(verbose_name='دیدگاه')),
                ('IsRead', models.BooleanField(default=False, verbose_name='خوانده شده/خوانده نشده')),
                ('IsActive', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
        ),
    ]
