# Generated by Django 3.2.9 on 2021-12-15 15:12

from django.db import migrations, models
import django.db.models.deletion
import home_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_products_tag', '0001_initial'),
        ('home_products_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home_products.models.upload_image_path, verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('Discount', models.CharField(max_length=120)),
                ('DiscountTime', models.DateTimeField(blank=True, default=None)),
                ('DiscountActive', models.BooleanField(default=False)),
                ('Tag', models.ManyToManyField(blank=True, to='home_products_tag.Tag', verbose_name='برچسب ها')),
                ('category', models.ManyToManyField(blank=True, to='home_products_category.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home_products.models.upload_image_gallery_path, verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home_products.product')),
            ],
        ),
    ]
