# Generated by Django 3.2.9 on 2021-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumbersType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='نام')),
                ('Icon', models.CharField(max_length=100, verbose_name='نام ایکون')),
            ],
            options={
                'verbose_name': 'نوع شماره',
                'verbose_name_plural': 'انواع شمارها',
            },
        ),
    ]
