# Generated by Django 3.2.9 on 2021-12-15 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mytag_cards_map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytag_cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='نام')),
                ('Country', models.CharField(max_length=50, verbose_name='کشور')),
                ('Province', models.CharField(max_length=50, verbose_name='استان')),
                ('City', models.CharField(max_length=50, verbose_name='شهر')),
                ('Address', models.TextField(verbose_name='ادرس')),
                ('Lat', models.CharField(max_length=100, verbose_name='lat')),
                ('Lng', models.CharField(max_length=100, verbose_name='lat')),
                ('MapZoom', models.CharField(default='16', max_length=20, verbose_name='زوم نقشه')),
                ('MapImg', models.ImageField(upload_to=mytag_cards_map.models.upload_image_path, verbose_name='عکس برای نشقه')),
                ('MapText', models.CharField(max_length=150, verbose_name='متن نشقه')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('By_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('DgTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytag_cards.card', verbose_name='کارت')),
            ],
            options={
                'verbose_name': 'نشقه',
                'verbose_name_plural': 'نقشه ها',
            },
        ),
    ]
