# Generated by Django 3.2.9 on 2021-12-06 20:25

from django.db import migrations, models
import mytag_cards_map.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytag_cards_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='MapImg',
            field=models.ImageField(upload_to=mytag_cards_map.models.upload_image_path, verbose_name='عکس برای نشقه'),
        ),
    ]
