# Generated by Django 3.2.9 on 2021-12-15 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(verbose_name='پرداخت شده /نشده')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('clientrefid', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('FullAddress', models.CharField(max_length=100, verbose_name='ادرس کامل')),
                ('ZipCode', models.CharField(max_length=100, verbose_name='کد پستی')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('Discount', models.CharField(max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_order.order', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جرییات محصول',
                'verbose_name_plural': 'اظلاعات جزیات محصولات',
            },
        ),
    ]
