# Generated by Django 3.2.9 on 2021-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_order', '0002_auto_20211214_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clientrefid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
