# Generated by Django 3.2.9 on 2021-12-15 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mytag_cards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytag_type', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImg', models.ImageField(blank=True, null=True, upload_to=mytag_cards.models.upload_image_path, verbose_name='عکس پروفایل')),
                ('FirstName', models.CharField(max_length=150, verbose_name='نام')),
                ('LastName', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('Company', models.CharField(max_length=120, verbose_name='نام کمپانی')),
                ('WorkName', models.CharField(max_length=100, verbose_name='شغل')),
                ('Bio', models.TextField(verbose_name='بایوگرافی')),
                ('UserName', models.CharField(max_length=150, verbose_name='نام کاربری')),
                ('IsActive', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('Views', models.IntegerField(default=0, verbose_name='بازدید')),
                ('Pro', models.BooleanField(default=False, verbose_name='پرو')),
                ('IsActiveUserName', models.BooleanField(default=False, verbose_name='فعال/غیرفعال بودن نام کاربری')),
                ('verification', models.BooleanField(default=False, verbose_name='تایید هویت')),
                ('CardId', models.IntegerField(verbose_name='ایدی کاربر در url')),
                ('BuildTime', models.DateTimeField(verbose_name='زمان ساخت کارت')),
                ('TypeOfCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytag_type.cardtype', verbose_name='نوع کارت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کارت',
                'verbose_name_plural': 'کارت ها',
            },
        ),
    ]
