# Generated by Django 3.2.9 on 2021-12-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytag_cards', '0001_initial'),
        ('mytag_cards_contactnumbers_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='نام')),
                ('Number', models.CharField(max_length=50, verbose_name='شماره')),
                ('IsActive', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytag_cards_contactnumbers_type.contactnumberstype', verbose_name='نوع')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_ContactNumbers', to='mytag_cards.card', verbose_name='کارت')),
            ],
        ),
    ]
