# Generated by Django 3.2.9 on 2021-11-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytag_cards', '0001_initial'),
        ('mytag_cards_socialnetworks_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='نام')),
                ('Url', models.CharField(max_length=250, verbose_name='ادرس شبکه اجتماعی')),
                ('IsActive', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytag_cards_socialnetworks_type.socialnetworktype', verbose_name='نوع شبکه')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytag_cards.card', verbose_name='کارت')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
